spring:
  datasource:
    username: ${JDBC_DATABASE_URL}
    password: ${JDBC_DATABASE_USERNAME}
    url: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/liquibase-master.xml
  h2:
    console:
      enabled: true
      path: /h2-console
planinarskidnevnik:
  frontend:
    path: ${FRONTEND_URL:http://localhost:3000}
server:
  servlet:
    context-path: /api